#pragma once

BEGIN(MyGame)

const unsigned int		g_iWinCX = 1280;
const unsigned int		g_iWinCY = 720;


#define TILECX 16
#define TILECY 16

enum SCENEID { SCENE_STATIC, SCENE_LOADING, SCENE_EDITOR, SCENE_STAGE, SCENE_END };
enum MODULE 
{ 
	MODULE_VIBUFFER,
	MODULE_TRANSFORM,

	MODULE_TEXTURE_DEFUALT,
	MODULE_TEXTURE_BOOKSHELF,
	MODULE_TEXTURE_FLOOR,
	MODULE_TEXTURE_FLOOR_MASKE,
	MODULE_TEXTURE_FLOOR_GRASS,
	MODULE_TEXTURE_FLOOR_MOSSY,
	MODULE_TEXTURE_FLOOR_WOOD,
	MODULE_TEXTURE_GRASS_GREEN,
	MODULE_TEXTURE_GRASS_GREEN_MASKE,
	MODULE_TEXTURE_GRASS_ASH,
	MODULE_TEXTURE_GRASS_ASH_MASKE,
	MODULE_TEXTURE_SING,
	MODULE_TEXTURE_STAIR_UP,
	MODULE_TEXTURE_STAIR_DOWN,
	MODULE_TEXTURE_STATUE_WITH_FLOOR,
	MODULE_TEXTURE_STATUE_WITH_WOOD,
	MODULE_TEXTURE_WALL,
	MODULE_TEXTURE_WALL_SEWERS,
	MODULE_TEXTURE_WELL,
	MODULE_TEXTURE_BLACK,
	MODULE_TEXTURE_DOOR,
	MODULE_TEXTURE_DOOR_LOCKED,
	MODULE_TEXTURE_FLOOR_BURND,
	MODULE_END, 
};




END